--TEST--
Check Vulkan constants are defined
--FILE--
<?php
$constants = [
    'FORMAT_B8G8R8A8_SRGB', 'BUFFER_USAGE_VERTEX_BUFFER',
    'SHADER_STAGE_VERTEX', 'SHADER_STAGE_FRAGMENT', 'SHADER_STAGE_COMPUTE',
    'PIPELINE_BIND_POINT_GRAPHICS', 'PIPELINE_BIND_POINT_COMPUTE',
    'IMAGE_LAYOUT_UNDEFINED', 'IMAGE_LAYOUT_PRESENT_SRC_KHR',
    'COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT',
    'PIPELINE_STAGE_ALL_COMMANDS', 'ACCESS_SHADER_WRITE',
    'QUERY_TYPE_TIMESTAMP', 'STENCIL_FACE_FRONT_AND_BACK',
    'API_VERSION_1_0', 'API_VERSION_1_3',
];

foreach ($constants as $name) {
    $fqn = "Vk\\Vk::$name";
    echo "$name: " . (defined($fqn) ? 'OK' : 'MISSING') . "\n";
}
?>
--EXPECT--
FORMAT_B8G8R8A8_SRGB: OK
BUFFER_USAGE_VERTEX_BUFFER: OK
SHADER_STAGE_VERTEX: OK
SHADER_STAGE_FRAGMENT: OK
SHADER_STAGE_COMPUTE: OK
PIPELINE_BIND_POINT_GRAPHICS: OK
PIPELINE_BIND_POINT_COMPUTE: OK
IMAGE_LAYOUT_UNDEFINED: OK
IMAGE_LAYOUT_PRESENT_SRC_KHR: OK
COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT: OK
PIPELINE_STAGE_ALL_COMMANDS: OK
ACCESS_SHADER_WRITE: OK
QUERY_TYPE_TIMESTAMP: OK
STENCIL_FACE_FRONT_AND_BACK: OK
API_VERSION_1_0: OK
API_VERSION_1_3: OK
